flight_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres_analytics') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'analytics') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'analytics') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'flight_analytics') }}"
      schema: bronze
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: bronze
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
